# Site
repository: sproogen/resume-theme
# favicon: images/favicon.ico

# Personal info
name: Md Rayhanur Rahman
title: Ph.D. Student at Computer Science, North Carolina State University
email: rayhan1.618@gmail.com
website: www.github.com/rayhanur-rahman

# Social links
# twitter_username: facespics
github_username:  rayhanur-rahman
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: chillwildlife
linkedin_username: rayhanur-rahman
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
researchgate_username: abc

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Rayhan and I am current doing my Ph.D. in NCSU

  I am most skilled in: <mark>C#</mark> and <mark>Python</mark>

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# Publications Section
# publications_title: Publications

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in networks and software engineering some of my other interests and hobbies are:
   - Rock climbing
   - Gaming
   - Knitting
   - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
